services:
    pythonenv:
        container_name: ${PROJECT_NAME}-pythonenv
        build:
            context: ..
            dockerfile: docker/pythonenv/Dockerfile
            args:
                PROJECT_DIR: ${PROJECT_DIR}
        environment:
            - "PROJECT_DIR=${PROJECT_DIR}"
        ports:
            - "8512:8000"  # jupyter port
        volumes:
            - ${PROJECT_DIR}:${PROJECT_DIR}
